(data-visualise)=
# 数据可视化

## 简介

> “简单的图表比其他任何工具都更能将信息传递到数据分析师的脑海中。” —— John Tukey

本章将教你如何使用 **[letsplot](https://lets-plot.org/)** 可视化你的数据。

使用代码创建数据可视化大致有两种方法：命令式（imperative），即构建你想要的内容；声明式（declarative），即描述你想要的内容。选择哪种方法涉及权衡：命令式库提供了灵活性，但以一定的冗长性为代价；声明式库可以快速绘制数据，但前提是数据格式正确，并且自定义特殊图表类型较为困难。Python有许多优秀的绘图包，包括可能是最强大的命令式绘图包 **matplotlib**。

然而，通过学习一个系统并在多个场景中应用，我们可以更快地取得进展——而声明式绘图的美妙之处在于它简单而有效地覆盖了大量标准图表。**letsplot** 实现了所谓的 **图形语法**，这是一种用于描述和构建图表的连贯声明式系统。

我们将从创建一个简单的散点图开始，并用它来介绍美学映射和几何对象——这些是 **letsplot** 的基本构建模块。然后，我们将引导你可视化单变量的分布，以及两个或多个变量之间的关系。最后，我们将介绍保存图表的方法和一些排障技巧。

### 准备工作

学习本章内容，你需要安装**letsplot**软件包。操作方法是，打开计算机的命令行，输入 `pip install lets-plot`，然后按回车键。

```{note}
在Visual Studio Code和Codespaces中，可通过依次点击 “视图” -> “终端” 来打开命令行。
```

请注意，在每个Python环境中，你只需安装一次软件包。

我们还需要安装 **pandas** 软件包，这个软件包用于处理数据，在后续内容中会经常用到。同样，你可以在命令行中运行 `pip install pandas` 来安装它。

最后，我们还需要一些数据（搞数据科学可离不开数据）。我们将使用帕尔默企鹅数据集。特别的是，这个数据集也能作为一个软件包来安装 —— 通常情况下是从文件中加载数据，但这个数据集在教程中太常用了，所以它已被整合到一个可安装的软件包中。运行 `pip install palmerpenguins` 即可获取这些数据。

我们接下来的任务是将这些软件包和数据集加载到Python会话中，你可以在Jupyter Notebook的Python笔记本单元格中操作，也可以写在脚本里，然后发送到交互式窗口，或者直接在交互式窗口中输入，再同时按下Shift键和回车键。以下是代码：

In [1]:
from lets_plot import *
from palmerpenguins import load_penguins

LetsPlot.setup_html()

这些代码行导入了**pandas**和**palmerpenguins**软件包的部分内容，接着导入了**letsplot**软件包的所有（`*`）函数。最后一行代码能让图表以HTML形式显示。

## 初步探索
拥有较长鳍状肢的企鹅，其体重相较于鳍状肢较短的企鹅，是更重还是更轻呢？你或许心中已有答案，但试着让你的答案更精确些。鳍状肢长度与体重之间的关系究竟如何？是正相关还是负相关？是呈线性关系，还是非线性关系？这种关系是否会因企鹅种类的不同而有所变化？那依据企鹅所栖息的岛屿不同，又会怎样呢？让我们创建可视化图表，用以解答这些问题。

### `penguins` 数据框

你可以利用 `palmerpenguins` 中的 `penguins` 数据框（即通过 `from palmerpenguins import load_penguins` 获取）来验证你对上述问题的答案。数据框是变量（列中）与观测值（行中）的矩形集合。`penguins` 包含由克里斯汀·戈尔曼博士及南极帕尔默站长期生态研究项目收集并公开的344条观测数据{cite:p}`horst2020palmerpenguins`。

为便于讨论，我们先定义一些术语：

- **变量**是指你能够测量的数量、性质或特性。

- **值**是指你测量变量时该变量所处的状态。变量的值可能会因每次测量而有所不同。

- **观测值**是指在相似条件下进行的一组测量值（通常，你会在同一时间对同一对象进行观测中的所有测量）。一个观测值会包含几个值，每个值与不同的变量相关联。我们有时会将观测值称为数据点。

- **表格数据**是一组值，每个值都与一个变量和一个观测值相关联。如果每个值都放在自己的 “单元格” 中，每个变量都在自己的列中，每个观测值都在自己的行中，那么表格数据就是 “整洁的”。

对于`penguins`数据，变量指的是所有企鹅共有的一种属性，而观测值指的是一只企鹅的所有属性。

在交互式窗口中输入数据框的名称，Python 将打印出其内容以便对其进行预览。

In [2]:
penguins = load_penguins()
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

若想换一种查看方式，以便看到每个变量的前几条观测值，可以使用 `penguins.head()` 。

In [3]:
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

`penguins` 数据集的变量包含以下内容：

1. `species`：企鹅的种类（阿德利企鹅、颊带企鹅或巴布亚企鹅）。

2. `flipper_length_mm`：企鹅鳍状肢的长度，单位为毫米。

3. `body_mass_g`：企鹅的体重，单位为克。

若要进一步了解 `penguins`，可运行 `help(load_penguins)` 打开其数据加载函数的帮助页面。

### 最终目标
本章我们的最终目标是重新创建以下可视化图表，该图表展示这些企鹅鳍状肢长度与体重之间的关系，同时将企鹅的种类纳入考量。

In [4]:
(
    ggplot(penguins, aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point(aes(color="species", shape="species"))
    + geom_smooth(method="lm")
    + labs(
        title="Body mass and flipper length",
        subtitle="Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
        x="Flipper length (mm)",
        y="Body mass (g)",
        color="Species",
        shape="Species",
    )
)

### 创建图表
我们逐步来重新创建这个图表。

使用 **letsplot** 时，你通过 `ggplot()` 函数开启一个绘图，定义一个绘图对象，然后为其添加 **图层** 。

`ggplot()` 的第一个参数是图表中要使用的数据集，所以 `ggplot(data = penguins)` 创建了一个空白图表，准备好展示 `penguins` 数据，但由于我们还没告诉它如何进行可视化，所以目前它是空的。因为它是空的，单独运行这行代码会报错：它就像一块空白画布，你将在上面绘制图表的其余图层。

```python
ggplot(data = penguins)
```

接下来，我们需要告诉 `ggplot()` 如何以可视化方式呈现数据中的信息。

`ggplot()` 函数的 `mapping` 参数定义了数据集中的变量如何映射到图表的视觉属性（**美学属性**）。`mapping` 参数总是在 `aes()` 函数中定义，而 `aes()` 的 `x` 和 `y` 参数指定将哪些变量映射到 x 轴和 y 轴。目前，我们只将鳍状肢长度映射到 `x` 美学属性，将体重映射到 `y` 美学属性。**letsplot** 会在 `data` 参数（在这种情况下是 `penguins`）中查找映射的变量。

同样，我们实际上还没有指定要绘制什么，所以运行

```python
ggplot(
  data = penguins,
  mapping = aes(x = "flipper_length_mm", y = "body_mass_g")
)
```

也会报错。这是因为我们在代码中还没有明确说明如何在图表上表示数据框中的观测值。

要做到这一点，我们需要定义一个 **几何对象**（geom）：即图表用于表示数据的几何图形。这些几何对象在 **letsplot** 中通过以 `geom_` 开头的函数来提供。

人们通常根据图表使用的几何对象类型来描述图表。例如，柱状图使用柱状几何对象（`geom_bar()`），折线图使用折线几何对象（`geom_line()`），箱线图使用箱线几何对象（`geom_boxplot()`），散点图使用点几何对象（`geom_point()`）等等。

`geom_point()` 函数为你的图表添加一层点，从而创建一个散点图。**letsplot** 有许多几何对象函数，每个函数都会为图表添加不同类型的图层。

In [5]:
(
    ggplot(data=penguins, mapping=aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point()
)

现在，我们得到了一个看似 “散点图” 的图形。虽然它还与我们的 “最终目标” 图形不完全一致，但借助这个图，我们可以开始回答引发此次探索的问题：“鳍状肢长度与体重之间呈现怎样的关系？” 这种关系似乎是正相关的（鳍状肢长度增加，体重也随之增加），且相当线性（这些点围绕一条直线聚集，而非曲线），同时相关性较强（围绕这条直线的离散程度不算太大）。总体而言，鳍状肢较长的企鹅体重通常更重。

值得一提的是，尽管我们绘制了 `penguins` 数据框中的所有内容，但其中有几行数据的值未定义，当然这些数据无法绘制。

### 添加美学属性与图层

散点图有助于展示两个数值变量之间的关系，但对于任意两个变量间看似存在的关系，我们最好持怀疑态度，并思考是否有其他变量能够解释或改变这种表面关系的本质。例如，鳍状肢长度与体重之间的关系是否会因企鹅种类的不同而有所差异呢？

让我们将种类信息融入到图表中，看看这是否能为这些变量间看似存在的关系揭示更多信息。我们将通过用不同颜色的点来表示不同种类的企鹅，从而实现这一点。

为达成此目的，我们需要修改美学属性还是几何对象呢？如果你猜 “在 `aes()` 内部的美学映射中进行修改”，那说明你已经初步掌握了使用 **letsplot** 创建数据可视化图表的技巧！要是没猜对，也别担心。

在本书中，你会绘制更多的图表，在绘制过程中有更多机会检验自己的直觉。

In [6]:
(
    ggplot(
        data=penguins,
        mapping=aes(x="flipper_length_mm", y="body_mass_g", color="species"),
    )
    + geom_point()
)

当一个分类变量映射到一种美学属性时，**letsplot** 会自动为该变量的每个唯一种类（这里是三种企鹅种类中的每一种）分配该美学属性的一个唯一值（这里是一种唯一颜色），这个过程称为**刻度缩放**或**标度调整**（scaling）。

**letsplot** 还会添加一个图例，用于说明哪些值对应哪些种类。

现在我们再添加一层：一条平滑曲线，用于展示体重与鳍状肢长度之间的关系。

在继续操作之前，请回顾上面的代码，并思考如何将其添加到我们现有的图表中。

由于这是一个表示我们数据的新几何对象，我们将添加一个新的几何对象作为点几何对象之上的一层：`geom_smooth()`。

并且我们将指定希望基于线性模型（`l`inear `m`odel）绘制最佳拟合线，通过 `method = "lm"` 来实现。

In [7]:
(
    ggplot(
        data=penguins,
        mapping=aes(x="flipper_length_mm", y="body_mass_g", color="species"),
    )
    + geom_point()
    + geom_smooth(method="lm")
)

我们成功添加了线条，但这个图和之前的图看起来不一样，因为之前的图整个数据集只有一条线，而不是为每种企鹅分别绘制线条。

当在 `ggplot()` 中，即在**全局**层面定义美学映射时，这些映射会传递到图的每个后续几何对象图层。

然而，**letsplot** 中的每个几何对象函数也可以接受一个 `mapping` 参数，这允许在**局部**层面进行美学映射，这些局部映射会添加到从全局层面继承而来的映射上。

由于我们希望点根据企鹅种类来上色，但不希望线条也按种类分开，所以我们应该只在 `geom_point()` 中指定 `color = species`：因此我们将其从全局的 `aes()` 中移除，仅添加到 `geom_point()` 里。

In [8]:
(
    ggplot(data=penguins, mapping=aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point(mapping=aes(color="species"))
    + geom_smooth(method="lm")
)

瞧！我们得到的图表已经很接近最终目标了，不过还不够完美。

我们仍需为每种企鹅使用不同形状，并优化标签。

一般来说，仅在图表中依靠颜色来呈现信息并非良策，因为不同人因色盲或其他色觉差异，对颜色的感知有所不同。因此，除了颜色之外，我们还可以将 `species` 映射到 `shape`（形状）这一美学属性上。

In [9]:
(
    ggplot(data=penguins, mapping=aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point(mapping=aes(color="species", shape="species"))
    + geom_smooth(method="lm")
)

请注意，图例也会自动更新，以体现点的不同形状。

最后，我们可以通过在新图层中使用 `labs()` 函数来改进图表的标签。`labs()` 的一些参数是不言自明的：`title` 为图表添加标题，`subtitle` 为图表添加副标题。其他参数与美学映射相对应，`x` 是 x 轴标签，`y` 是 y 轴标签，`color` 和 `shape` 则定义了图例的标签。

In [10]:
(
    ggplot(data=penguins, mapping=aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point(aes(color="species", shape="species"))
    + geom_smooth(method="lm")
    + labs(
        title="Body mass and flipper length",
        subtitle="Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
        x="Flipper length (mm)",
        y="Body mass (g)",
        color="Species",
        shape="Species",
    )
)

我们终于得到了一张与 “最终目标” 完全相符的图表！

### 练习

1. `penguins` 数据框中有多少行？多少列？

2. `penguins` 数据框中的 `bill_depth_mm` 变量描述的是什么？通过查看 `load_penguins()` 的帮助文档来了解，例如运行 `help(load_penguins)`。

3. 制作一个 `bill_depth_mm` 与 `bill_length_mm` 的散点图。也就是说，制作一个以 `bill_depth_mm` 为 y 轴，`bill_length_mm` 为 x 轴的散点图。描述这两个变量之间的关系。

4. 如果制作一个 `species` 与 `bill_depth_mm` 的散点图会发生什么？哪种几何对象可能是更好的选择？

5. 为什么下面的代码会报错，要如何修正？

    ```python
    (ggplot(data = penguins) + 
      geom_point())
    ```

6. 给你在上一题练习中制作的图添加以下说明：“数据来自 palmerpenguins 包。” 提示：查看 `labs()` 的文档。

7. 重新创建以下可视化图表。`bill_depth_mm` 应该映射到什么美学属性上？应该在全局层面还是几何对象层面进行映射？

In [11]:
(
    ggplot(data=penguins, mapping=aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point(aes(color="bill_depth_mm"))
    + geom_smooth()
)

8. 在脑海中运行这段代码，预测输出的图表会是什么样子。然后，在Python中运行代码，检查你的预测是否正确。

    ```python
    (ggplot(
      data = penguins,
      mapping = aes(x = "flipper_length_mm", y = "body_mass_g", color = "island")
    ) +
      geom_point() +
      geom_smooth(se = False)
    )
    ```

9. 这两个图表看起来会不一样吗？为什么会或为什么不会？

    ```python
    (ggplot(
      data = penguins,
      mapping = aes(x = "flipper_length_mm", y = "body_mass_g")
    ) +
      geom_point() +
      geom_smooth()
    )
    ```
    ```python
    (ggplot() +
      geom_point(
        data = penguins,
        mapping = aes(x = "flipper_length_mm", y = "body_mass_g")
      ) +
      geom_smooth(
        data = penguins,
        mapping = aes(x = "flipper_length_mm", y = "body_mass_g")
      )
    )
    ```

## **letsplot** calls

As we move on from these introductory sections, we'll transition to a more concise expression of **letsplot** code.

So far we've been very explicit, which is helpful when you are learning:

```python
(ggplot(
  data = penguins,
  mapping = aes(x = "flipper_length_mm", y = "body_mass_g")
) +
  geom_point())
```

Typically, the first one or two arguments to a function are so important that you should know them by heart.
The first two arguments to `ggplot()` are `data` and `mapping`, in the remainder of the book, we won't supply those names—the way the function is written, Python knows to expect these variables because of their position. Not writing them in saves typing, and, by reducing the amount of extra text, makes it easier to see what's different between plots.
That's a really important programming concern that we'll come back to later.

Rewriting the previous plot more concisely yields:

```python
(
    ggplot(penguins, aes(x = "flipper_length_mm", y = "body_mass_g")) + 
  geom_point()
)
```

## visualising distributions

How you visualise the distribution of a variable depends on the type of variable: categorical or numerical.

### A categorical variable

A variable is **categorical** if it can only take one of a small set of values.
To examine the distribution of a categorical variable, you can use a bar chart.
The height of the bars displays how many observations occurred with each `x` value.

In [ ]:
(ggplot(penguins, aes(x="species")) + geom_bar())

You may have seen earlier that the *data type* of the `"species"` column is string. Ideally, we want it to be categorical, so that there's no confusion about the fact that we're dealing with a finite number of mutually exclusive groups here. Another advantage is that it allows plotting tools to realise what kind of data it is working with.

We can transform the variable to a categorical variable using **pandas** like so:

In [ ]:
penguins["species"] = penguins["species"].astype("category")
penguins.head()

You will learn more about categorical variables later in the book.


### A numerical variable

A variable is **numerical** (or quantitative) if it can take on a wide range of numerical values, and it is sensible to add, subtract, or take averages with those values. Numerical variables can be continuous or discrete.

One commonly used visualisation for distributions of continuous variables is a histogram.

In [ ]:
(ggplot(penguins, aes(x="body_mass_g")) + geom_histogram(binwidth=200))

A histogram divides the x-axis into equally spaced bins and then uses the height of a bar to display the number of observations that fall in each bin.
In the graph above, the tallest bar shows that 39 observations have a `body_mass_g` value between 3,500 and 3,700 grams, which are the left and right edges of the bar.

You can set the width of the intervals in a histogram with the binwidth argument, which is measured in the units of the `x` variable.
You should always explore a variety of binwidths when working with histograms, as different binwidths can reveal different patterns.
In the plots below a binwidth of 20 is too narrow, resulting in too many bars, making it difficult to determine the shape of the distribution.
Similarly, a binwidth of 2,000 is too high, resulting in all data being binned into only three bars, and also making it difficult to determine the shape of the distribution.
A binwidth of 200 provides a sensible balance, but you should always look at your data a few different ways, especially with histograms as they can be misleading.

An alternative visualisation for distributions of numerical variables is a density plot.
A density plot is a smoothed-out version of a histogram and a practical alternative, particularly for continuous data that comes from an underlying smooth distribution.
We won't go into how `geom_density()` estimates the density (you can read more about that in the function documentation), but let's explain how the density curve is drawn with an analogy.
Imagine a histogram made out of wooden blocks.
Then, imagine that you drop a cooked spaghetti string over it.
The shape the spaghetti will take draped over blocks can be thought of as the shape of the density curve.
It shows fewer details than a histogram but can make it easier to quickly glean the shape of the distribution, particularly with respect to modes and skewness.

In [ ]:
(ggplot(penguins, aes(x="body_mass_g")) + geom_density())

### Exercises

1.  Make a bar plot of `"species"` of `penguins`, where you assign `"species"` to the `y` aesthetic.
    How is this plot different?

2.  How are the following two plots different?
    Which aesthetic, `color` or `fill`, is more useful for changing the color of bars?

    ```Python

    (ggplot(penguins, aes(x = species)) +
      geom_bar(color = "red"))

    (ggplot(penguins, aes(x = species)) +
      geom_bar(fill = "red"))
    ```

3.  What does the `bins` argument in `geom_histogram()` do?

## Visualising Relationships

To visualise a relationship we need to have at least two variables mapped to aesthetics of a plot—though you should remember that correlation is not causation, and causation is not correlation!

In the following sections you will learn about commonly used plots for visualising relationships between two or more variables and the geoms used for creating them.

### A numerical and a categorical variable

To visualise the relationship between a numerical and a categorical variable we can use side-by-side box plots.

A **boxplot** is a type of visual shorthand for measures of position within a distribution (percentiles).

It is also useful for identifying potential outliers. Each boxplot consists of:

-   A box that indicates the range of the middle half of the data, a distance known as the interquartile range (IQR), stretching from the 25th percentile of the distribution to the 75th percentile.
    In the middle of the box is a line that displays the median, i.e. 50th percentile, of the distribution.
    These three lines give you a sense of the spread of the distribution and whether or not the distribution is symmetric about the median or skewed to one side.

-   Visual points that display observations that fall more than 1.5 times the IQR from either edge of the box.
    These outlying points are unusual so are plotted individually.

-   A line (or whisker) that extends from each end of the box and goes to the farthest non-outlier point in the distribution.


Let's take a look at the distribution of body mass by species using `geom_boxplot()`:

In [ ]:
(ggplot(penguins, aes(x="species", y="body_mass_g")) + geom_boxplot())

Alternatively, we can make probability density plots with `geom_density()`.

In [ ]:
(ggplot(penguins, aes(x="body_mass_g", color="species")) + geom_density(size=2))

We've also customized the thickness of the lines using the `size` argument in order to make them stand out a bit more against the background.

Additionally, we can map `species` to both `color` and `fill` aesthetics and use the `alpha` aesthetic to add transparency to the filled density curves.
This aesthetic takes values between 0 (completely transparent) and 1 (completely opaque).
In the following plot it's *set* to 0.5.

In [ ]:
(
    ggplot(penguins, aes(x="body_mass_g", color="species", fill="species"))
    + geom_density(alpha=0.5)
)

Note the terminology we have used here:

-   We *map* variables to aesthetics if we want the visual attribute represented by that aesthetic to vary based on the values of that variable.
-   Otherwise, we *set* the value of an aesthetic.

### Two categorical variables

We can use stacked bar plots to visualise the relationship between two categorical variables.

For example, the following two stacked bar plots both display the relationship between `island` and `species`, or specifically, visualising the distribution of `species` within each island.

The first plot shows the frequencies of each species of penguins on each island.
The plot of frequencies show that there are equal numbers of Adelies on each island.

But we don't have a good sense of the percentage balance within each island.

In [ ]:
(ggplot(penguins, aes(x="island", fill="species")) + geom_bar())

The second plot is a relative frequency plot, created by setting `position = "fill"` in the geom is more useful for comparing species distributions across islands since it's not affected by the unequal numbers of penguins across the islands.

Using this plot we can see that Gentoo penguins all live on Biscoe island and make up roughly 75% of the penguins on that island, Chinstrap all live on Dream island and make up roughly 50% of the penguins on that island, and Adelie live on all three islands and make up all of the penguins on Torgersen.

In [ ]:
(ggplot(penguins, aes(x="island", fill="species")) + geom_bar(position="fill"))

In creating these bar charts, we map the variable that will be separated into bars to the `x` aesthetic, and the variable that will change the colors inside the bars to the `fill` aesthetic.

### Two numerical variables

So far you've learned about scatterplots (created with `geom_point()`) and smooth curves (created with `geom_smooth()`) for visualising the relationship between two numerical variables.
A scatterplot is probably the most commonly used plot for visualising the relationship between two numerical variables.

In [ ]:
(ggplot(penguins, aes(x="flipper_length_mm", y="body_mass_g")) + geom_point())

### Three or more variables

As we saw already, we can incorporate more variables into a plot by mapping them to additional aesthetics.

For example, in the following scatterplot the colors of points represent species and the shapes of points represent islands.

In [ ]:
(
    ggplot(penguins, aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point(aes(color="species", shape="island"))
)

However adding too many aesthetic mappings to a plot makes it cluttered and difficult to make sense of.

Another way, which is particularly useful for categorical variables, is to split your plot into **facets** (also known as **small multiples**), subplots that each display one subset of the data.

To facet your plot by a single variable, use `facet_wrap()`.

The first argument of `facet_wrap()` tells the function what variable to have in successive charts. The variable that you pass to `facet_wrap()` should be categorical.

In [ ]:
(
    ggplot(penguins, aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point(aes(color="species", shape="species"))
    + facet_wrap(facets="island")
)

You will learn about many other geoms for visualising distributions of variables and relationships between them in later chapters.

### Exercises

1.  Make a scatterplot of `bill_depth_mm` vs. `bill_length_mm` and color the points by `species`.
    What does adding coloring by species reveal about the relationship between these two variables?
    What about faceting by `species`?

2.  Why does the following yield two separate legends?
    How would you fix it to combine the two legends?

    ```python
    (
        ggplot(
          data = penguins,
          mapping = aes(
            x = "bill_length_mm", y = "bill_depth_mm", 
            color = "species", shape = "species"
          )
        ) +
          geom_point() +
          labs(color = "Species")
    )
    ```

3.  Create the two following stacked bar plots.
    Which question can you answer with the first one?
    Which question can you answer with the second one?

    ```python
    ggplot(penguins, aes(x = "island", fill = "species")) +
      geom_bar(position = "fill")
    ggplot(penguins, aes(x = "species", fill = "island")) +
      geom_bar(position = "fill")
    ```

## Saving your plots

Once you've made a plot, you might want to save it as an image that you can use elsewhere.
That's the job of `ggsave()`, which will save the plot most recently created to disk:

In [ ]:
plotted_data = (
    ggplot(penguins, aes(x="flipper_length_mm", y="body_mass_g")) + geom_point()
)
ggsave(plotted_data, filename="penguin-plot.svg")

This saved the figure to disk at the location shown—by default it's in a subdirectory called "lets-plot-images".

We used the file format "svg". There are lots of output options to choose from to save your file to. Remember that, for graphics, *vector formats* are generally better than *raster formats*. In practice, this means saving plots in svg or pdf formats over jpg or png file formats. The svg format works in a lot of contexts (including Microsoft Word) and is a good default. To choose between formats, just supply the file extension and the file type will change automatically, eg "chart.svg" for svg or "chart.png" for png. You can also save figures in HTML format.

If you're using a raster format then you'll need to specify how big the figure is via the *scale* keyword argument.

In [ ]:
import shutil

shutil.rmtree("lets-plot-images")

### Exercises

1. Save the figure above as a PNG. Try varying the scale.

## Common Problems

As you start to run code, you're likely to run into problems.
Don't worry—it happens to everyone.
We have all been writing Python code for years, but every day we still write code that doesn't work on the first try!

Start by carefully comparing the code that you're running to the code in the book: A misplaced character can make all the difference!
Make sure that every `(` is matched with a `)` and every `"` is paired with another `"`. In  Visual Studio Code, you can get extensions that colour match brackets so you can easily see if you closed them or not.

Sometimes you'll run the code and nothing happens.

For those coming from the R statistical programming language, you may be concerned about getting your `+` in the wrong place. Have no fear, however, as in the syntax for **letsplot** the `+` can go at the start or the end of the line.


If you're still stuck, try the help.
You can get help about any Python function by running `help(function_name)` in the interactive window.
Don't worry if the help doesn't seem that helpful - instead skip down to the examples and look for code that matches what you're trying to do.

If you're still stuck, check out the **letsplot** [documentation](https://lets-plot.org/) or doing a Google search (especially helpful for error messages).

## Summary

In this chapter, you've learned the basics of data visualisation with **letsplot**.
We started with the basic idea that underpins **letsplot**: a visualisation is a mapping from variables in your data to aesthetic properties like position, colour, size and shape.
You then learned about increasing the complexity and improving the presentation of your plots layer-by-layer.
You also learned about commonly used plots for visualising the distribution of a single variable as well as for visualising relationships between two or more variables, by leveraging additional aesthetic mappings and/or splitting your plot into small multiples using faceting.

We'll use visualisations again and again throughout this book, introducing new techniques as we need them as well as do a deeper dive into creating visualisations with **letsplot** in subsequent chapters.

With the basics of visualisation under your belt, in the next chapter we're going to switch gears a little and give you some practical workflow advice.
We intersperse workflow advice with data science tools throughout this part of the book because it'll help you stay organised as you write more Python code.